# Generated by Django 4.2.29 on 2026-03-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
